<h1 class="text-center">Création d'un nouvel article</h1>

<form method="post" class="post-form">
    <fieldset>
        <div class="form-group">
            <label for="title">Titre</label>
            <input type="text" name="title" id="title">
        </div>
        <div class="form-group">
            <label for="content">Article</label>
            <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </div>
        <div class="form-group">
            <label for="category">Catégorie</label>
            <select name="category_id" id="category">
                <?php foreach ($categories as $category): ?>
                    <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
                <?php endforeach ?>
            </select>
        </div>
        <button class="button button-primary">Ajouter</button>
    </fieldset>
</form>