<h1 class="text-center">Modification d'un article existant</h1>

<form method="post" class="post-form">
    <fieldset>
        <input type="hidden" name="post_id" value="<?= $post['id'] ?>">
        <div class="form-group">
            <label for="title">Titre</label>
            <input type="text" name="title" id="title" value="<?= $post['title'] ?>">
        </div>
        <div class="form-group">
            <label for="content">Article</label>
            <textarea name="content" id="content" cols="30" rows="10"><?= $post['content'] ?></textarea>
        </div>
        <button class="button button-primary">Modifier</button>
    </fieldset>
</form>