<h1 class="text-center">Connexion</h1>

<form action="login.php" method="post">
    <fieldset>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
        </div>
        <div class="form-group">
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password">
        </div>
        <button class="button button-primary">Se connecter</button>
    </fieldset>
</form>