<h1 class="text-center">Inscription</h1>

<form action="register.php" method="post">
    <fieldset>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email">
        </div>
        <div class="form-group">
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password">
        </div>
        <div class="form-group">
            <label for="firstname">Prénom</label>
            <input type="text" name="firstname" id="firstname">
        </div>
        <div class="form-group">
            <label for="lastname">Nom</label>
            <input type="text" name="lastname" id="lastname">
        </div>
        <button class="button button-primary">S'inscrire</button>
    </fieldset>
</form>