<h1><?= htmlspecialchars($post['title']) ?></h1>

<nav>
    <a href="edit_post.php?id=<?= $post['id'] ?>"><i class="fa fa-edit"></i> Editer l'article</a>
</nav>

<article>
    <header>
        Rédigé par <?= $post['firstname'] ?> <?= $post['lastname'] ?> le <?= $post['creation_date'] ?>
    </header>
    <hr>
    <?= nl2br(htmlspecialchars($post['content'])) ?>
</article>

<hr>

<section id="comment-list">
    <h2>Liste des commentaires</h2>
    <form method="post" action="add_comment.php">
        <input type="hidden" name="post_id" value="<?= $post['id'] ?>">
        <fieldset>
            <div class="form-group">
                <label for="username">Votre pseudo</label>
                <input type="text" id="username" name="username">
            </div>
            <div class="form-group">
                <label for="content">Commentaire</label>
                <textarea name="content" id="content" cols="30" rows="10"></textarea>
            </div>
            <button class="button button-primary">Envoyer</button>
        </fieldset>
    </form>
    
    <?php if (empty($comments)): ?>
        <p>Aucun commentaire pour le moment</p>
    <?php else: ?>
        <ul>
            <?php foreach ($comments as $comment): ?>
                <li>
                    <article>
                        <header>
                            <h3><?= $comment['username'] ?></h2>
                            <small>Le <?= $comment['creation_date'] ?></small>
                        </header>
                        <?= $comment['content'] ?>
                    </article>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
</section>